# NUMPY LIBRARY


In [100]:
import numpy as np

In [101]:
#creating 0d array- scalar array
arr1= np.array(15)
arr1

array(15)

In [102]:
#creating 1 d array
a = np.array([34,53,65,97])
a

array([34, 53, 65, 97])

In [103]:
#to find the type of an array
type(a)

numpy.ndarray

In [104]:
#Dimension of array
print(a.ndim)

1


In [105]:
#creating 3d array
c = np.array([[(10,20,30),(40,50,60)],[(70,80,90),(41,51,61)]],dtype=float)
print(c)

[[[10. 20. 30.]
  [40. 50. 60.]]

 [[70. 80. 90.]
  [41. 51. 61.]]]


In [106]:
#Dimension of 3d array
print(c.ndim)

3


In [107]:
#Defining number of dimensions 
x1 = np.array([11, 12, 13, 14], ndmin=3)
x1

array([[[11, 12, 13, 14]]])

In [108]:
#creating a array of zeros
x=np.zeros((6,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [109]:
#creating a array of ones
x=np.ones((5,8))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [110]:
#Eye Function:   Returns array filled with zeros except in the kth diagonal, whose values are equal to 1
a= np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [111]:
a= np.eye(4,6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [112]:
a=np.eye(3,k=-2)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [113]:
a=np.eye(6,k=3)
print(a)

[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [114]:
a = np.eye(6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


# Accessing array element

In [115]:
# Accessing 1 d array
a = np.array([18, 28, 38, 48])

print(a[0])
print(a[2])
print(a[2] + a[3])

18
38
86


In [116]:
#Access 2-D Arrays
a=np.array([[10,20,30,40,50], [60,70,80,90,100]])
print(a[0,1])
print(a[1,2])
print(a[0,3])

20
80
40


In [117]:
#Access 3-D Arrays
a = np.array([[[15, 12, 23], [43, 45, 65]], [[72, 82, 93], [14, 17, 19]]])

print(a[1, 0, 2])
print(a[0,1,1])
print(a[1,1,2])

93
45
19


In [118]:
#Negative Indexing
a = np.array([[12,33,44,55], [66,57,93,12]])

print(a[1, -3])
print(a[0,-2])
print(a[1,2])

57
44
93


# slicing arrays

In [119]:
a = np.array([11, 22, 33, 44,55,66,77])
print(a[0:5])
print(a[1:])
print(a[:7])
print(a[-4:-1])
print(a[1:5:2])
print(a[::3])
print(a[2:6])

[11 22 33 44 55]
[22 33 44 55 66 77]
[11 22 33 44 55 66 77]
[44 55 66]
[22 44]
[11 44 77]
[33 44 55 66]


In [120]:
#Slicing 2-D Arrays
a = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])

print(a[0, 0:4])
print(a[1,1:5])

[10 20 30 40]
[ 70  80  90 100]


In [121]:
a = np.array([[21, 42, 13, 44, 55], [26, 37, 58, 79, 30]])

print(a[0:2,4])
print(a[0:2, 1:4])

[55 30]
[[42 13 44]
 [37 58 79]]
